# Generated by Django 4.1.7 on 2023-07-07 16:18

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "db.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_func),
    ]
